language: rust
rust:
  - 1.39.0  # minimal supported version
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache:
  - cargo

before_install:
  - cd aeron
  - >
    SOURCE_DIR=$(pwd);
    mkdir build;
    cd build;
    cmake -G "CodeBlocks - Unix Makefiles" $SOURCE_DIR;
    make aeronmd;
    sudo mv binaries/aeronmd /usr/bin;
    sudo chmod +w /dev/shm;

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features --workspace -- -D warnings #-W clippy::nursery
  # TODO: change --lib to --all-targets for the integration tests to run
  - cargo test --all-features --lib -- --test-threads=1
